apiVersion: taas/v1
kind: Mapping

metadata:
  name: mongo-demo-sink
  owner: demo
  revision: 4
  updatedAt: 2026-03-04T05:54:26.677077190Z
  lastPublishedAt: 2026-03-04T05:54:26.677077190Z
  lastPublishResult: SUCCESS
  commitSha: f19226e

selector:
  connectorName: mongo-demo-sink

output:
  mode: CONNECT_MAP
  complexTypes: NATIVE_JSON

fields:
  - target: claimId
    path: "$.claim.id"
    type: STRING
    required: true
  - target: submittedAt
    path: "$.meta.lastUpdated"
    type: STRING
    required: false
  - target: amount
    path: "$.claim.totalAmount.value"
    type: STRING
    required: false
