apiVersion: taas/v1
kind: Mapping

metadata:
  name: jdbc-claims-sink
  owner: platform-team
  revision: 3
  updatedAt: 2026-03-03T15:30:02.128455253Z
  lastPublishedAt: 2026-03-03T15:30:02.128455253Z
  lastPublishResult: SUCCESS
  commitSha: 2f22c94

selector:
  connectorName: jdbc-claims-sink

output:
  mode: CONNECT_MAP
  complexTypes: NATIVE_JSON

fields:
  - target: claimId
    path: "$.claim.id"
    type: STRING
    required: false
  - target: memberId
    path: "$.claim.member.id"
    type: STRING
    required: false
  - target: providerId
    path: "$.claim.provider.id"
    type: STRING
    required: false
  - target: claimAmount
    path: "$.claim.totalAmount"
    type: STRING
    required: false
  - target: claimStatus
    path: "$.claim.status"
    type: STRING
    required: false
