apiVersion: taas/v1
kind: Mapping

metadata:
  name: mongo-orders-sink
  owner: order-team
  revision: 2
  updatedAt: 2026-03-03T12:32:12.470756252Z
  lastPublishedAt: 2026-03-03T12:32:12.470756252Z
  lastPublishResult: SUCCESS
  commitSha: null

selector:
  connectorName: mongo-orders-sink

output:
  mode: CONNECT_MAP
  complexTypes: NATIVE_JSON

fields:
  - target: orderId
    path: "$.order.id"
    type: LONG
    required: true
  - target: customerId
    path: "$.order.customer.id"
    type: LONG
    required: true
  - target: orderAmount
    path: "$.order.amount"
    type: DOUBLE
    required: false
  - target: createdAt
    path: "$.order.createdAt"
    type: DATE
    required: false
  - target: currency
    path: "$.order.currency"
    type: STRING
    required: false
