apiVersion: taas/v1
kind: Mapping

metadata:
  name: test-sink
  owner: platform-team
  ownerTeam: "platform-team"
  dataClass: INTERNAL
  governanceNotes: null
  revision: 2
  updatedAt: 2026-03-07T09:20:01.096426221Z
  lastPublishedAt: 2026-03-07T09:20:01.096426221Z
  lastPublishResult: SUCCESS
  commitSha: null

selector:
  connectorName: test-sink

output:
  profile: JDBC
  mode: STRUCT
  complexTypes: JSON_STRING

fields:
  - target: id
    path: "$.claim.id"
    type: STRING
    required: false
  - target: amount
    path: "$.claim.amount"
    type: STRING
    required: false
  - target: id2
    path: "$.patient.id"
    type: STRING
    required: false
